# Generated by Django 4.2.4 on 2024-05-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_present", models.BooleanField(default=False)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.gym"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_present", models.BooleanField(default=False)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.gym"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.member"
                    ),
                ),
            ],
        ),
    ]
