# Generated by Django 4.2.4 on 2024-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginsystem",
            name="is_employee",
        ),
        migrations.RemoveField(
            model_name="loginsystem",
            name="is_member",
        ),
        migrations.RemoveField(
            model_name="loginsystem",
            name="is_owner",
        ),
        migrations.RemoveField(
            model_name="loginsystem",
            name="is_trainer",
        ),
        migrations.AddField(
            model_name="loginsystem",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("owner", "Software Owner"),
                    ("trainer", "Trainer"),
                    ("member", "Member"),
                    ("staff", "Software Staff"),
                    ("other", "Other"),
                ],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
