# Generated by Django 4.2.4 on 2024-05-14 13:30

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("purchase_date", models.DateField()),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[("New", "New"), ("Used", "Used")], max_length=4
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="equipment_photos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "gym_id",
                    models.CharField(
                        default=api.models.generate_gym_id,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gym_name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=250)),
                ("gym_address", models.TextField()),
                ("establishment_date", models.DateField()),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="gym_logos/"),
                ),
                ("gym_qr", models.ImageField(blank=True, upload_to="gym_qr/")),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "member_id",
                    models.CharField(
                        default=api.models.generate_member_id,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("member_name", models.CharField(max_length=250)),
                (
                    "member_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("member_age", models.IntegerField()),
                ("member_weight", models.FloatField()),
                ("member_height", models.IntegerField()),
                ("member_date_of_birth", models.DateField()),
                ("member_address", models.CharField(max_length=100)),
                ("member_photo", models.ImageField(upload_to="member_photos/")),
                ("member_qr", models.ImageField(upload_to="member_qr/")),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price_paid", models.DecimalField(decimal_places=2, max_digits=8)),
                ("payment_method", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_key", models.CharField(max_length=50)),
                ("license_expiry_date", models.DateField()),
                ("payment_method", models.CharField(max_length=50)),
                ("billing_address", models.TextField()),
                (
                    "payment_confirmation",
                    models.FileField(upload_to="payment_confirmations/"),
                ),
                ("gym_contact_number", models.CharField(max_length=20)),
                ("gym_email", models.EmailField(max_length=254)),
                ("active_users_count", models.IntegerField()),
                ("training_and_support_requests", models.TextField()),
                ("admin_username", models.CharField(max_length=50)),
                ("admin_email", models.EmailField(max_length=254)),
                ("admin_password", models.CharField(max_length=50)),
                ("integration_preferences", models.TextField(blank=True)),
                ("usage_agreement", models.FileField(upload_to="usage_agreements/")),
                ("feedback_on_features", models.TextField(blank=True)),
                ("improvement_suggestions", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        default=api.models.generate_staff_id,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("staff_name", models.CharField(max_length=250)),
                ("staff_address", models.CharField(max_length=250)),
                (
                    "staff_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("staff_age", models.IntegerField()),
                ("staff_position", models.CharField(max_length=100)),
                ("staff_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("staff_date_of_hire", models.DateField()),
                (
                    "staff_photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
                ),
                ("staff_qr", models.ImageField(upload_to="staff_qr/")),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Afternoon", "Afternoon"),
                            ("Evening", "Evening"),
                            ("Night", "Night"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "trainer_id",
                    models.CharField(
                        default=api.models.generate_trainer_id,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trainer_name", models.CharField(max_length=250)),
                ("speciality", models.CharField(max_length=100)),
                ("years_of_experience", models.IntegerField()),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("certification", models.CharField(max_length=250)),
                ("contact_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=250)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="trainer_profile_pics/"
                    ),
                ),
                (
                    "trainer_qr",
                    models.ImageField(blank=True, null=True, upload_to="trainer_qr/"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.gym"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration_in_weeks", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("target_audience", models.CharField(max_length=100)),
                ("difficulty_level", models.CharField(max_length=50)),
                ("goals", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="workout_plan_photos/"
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.gym",
                    ),
                ),
                (
                    "included_equipment",
                    models.ManyToManyField(
                        related_name="workout_plans", to="api.equipment"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.trainer"
                    ),
                ),
            ],
        ),
    ]
